name: GitHub Actions Vercel Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:

jobs:
  Test:
    uses: Yellowbunbunz/CISE_Group03/.github/workflows/test.yml@feat/vercel-development

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
    - uses: actions/checkout@v3
      with:
        path: ./frontend 

    - name: Install Vercel CLI
      run: npm install --global vercel@canary

    - name: Pull Vercel Environment Information
      run: cd frontend && vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: cd frontend && vercel build --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Project Artifacts to Vercel
      run: cd frontend && vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}